### ISSUE TITLE
What are the different error codes it can return? Can we have a sample on handling those scenarios?

### ISSUE THREAD

**Issue by faisalaltell12** [hennessyevan/expo-user-identity#1]

**Comment by hennessyevan** [comment]
Hey @faisalaltell12 

On iOS, it can return `NO_ACCOUNT_ACCESS_ERROR` `NS_ERROR` or `UNKNOWN_ERROR`
On Android, it just forwards whatever the error code is from android.

In terms of samples, it really is up to what you'd like to do in your application, you could present a notification to the user to sign in or a warning, etc.. This module takes no opinions there.
