### ISSUE TITLE
EAS Build Production Error

### ISSUE THREAD

**Issue by faisalaltell12** [hennessyevan/expo-user-identity#2]
Running eas build with profile set to production as shown below causes an error:
``` eas build --profile production --platform ios ```

``` error: exportArchive: exportOptionsPlist error for key "iCloudContainerEnvironment": value "Development" is not allowed ```

Here is a copy of my app.json if needed?
<img width="329" alt="image" src="https://github.com/hennessyevan/expo-user-identity/assets/89555130/0c1802ab-d6a3-4c7e-85db-9e35dbe60911">

Not sure if I am missing anything or if I set it up correctly. Your guidance is very much appreciated!

**Comment by faisalaltell12** [comment]
@hennessyevan Resolved by adjusting "plugins" in app.json to:

```
    "plugins": [
      [
        "expo-user-identity",
        {          
          "iCloudContainerEnvironment": "Production"
        }
      ]
    ]
```

**Comment by hennessyevan** [comment]
Right! The default is "Development". I can make that more clear in the readme. Thanks @faisalaltell12
